using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Security.Cryptography;
using System.Text.Json;

namespace pk3DS.WinForms;

/// <summary>
/// Applies compact catch-zone patch manifests to files extracted from the user's own ROM dump.
///
/// Legacy catch_zone_templates folders are supported only as a developer migration source:
/// when no patch manifest exists, a manifest can be generated by comparing the clean files
/// extracted by pk3DS against the modified legacy template files. Production releases only
/// need the generated catch_zone_patches manifests.
/// </summary>
internal static class CatchZonePatchSync
{
    private const int CurrentFormat = 1;
    private const string PatchRootName = "catch_zone_patches";
    private const string LegacyTemplateRootName = "catch_zone_templates";

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        PropertyNameCaseInsensitive = true,
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
        WriteIndented = true,
    };

    private static readonly Dictionary<string, string[]> LegacyFolderNames = new(StringComparer.OrdinalIgnoreCase)
    {
        ["encdata"] = ["encdata", "2_g", "3_g"],
        ["mapGR"] = ["mapGR", "1_g", "9_g"],
    };

    internal static bool HasPatchForCurrentGame()
    {
        string path = GetPatchManifestPath();
        return path.Length != 0 && File.Exists(path);
    }

    internal static bool HasLegacyTemplateForCurrentGame()
    {
        if (!IsGen6XYOrORAS())
            return false;

        return GetLegacyTemplateSourceFolder("encdata").Length != 0
            || GetLegacyTemplateSourceFolder("mapGR").Length != 0
            || GetLegacyRawTemplateSourceFolder().Length != 0;
    }

    internal static string BuildCurrentGamePatchManifestFromLegacyTemplates(string romfsPath)
    {
        if (!IsGen6XYOrORAS())
            throw new InvalidOperationException("Catch-zone patches are only supported for XY/ORAS.");
        if (string.IsNullOrWhiteSpace(romfsPath) || !Directory.Exists(romfsPath))
            throw new DirectoryNotFoundException("The loaded RomFS folder could not be found.");
        if (!HasLegacyTemplateForCurrentGame())
            throw new DirectoryNotFoundException("No legacy catch-zone template folder was found.");

        string game = GetGameFolderName();
        var manifest = new CatchZonePatchManifest
        {
            Format = CurrentFormat,
            Game = game,
        };

        foreach (string scope in new[] { "encdata", "mapGR" })
        {
            string targetRoot = GetLegacyTemplateSourceFolder(scope);
            if (targetRoot.Length == 0)
                continue;

            string sourceRoot = Path.GetFullPath(scope);
            if (!Directory.Exists(sourceRoot))
                throw new DirectoryNotFoundException(
                    $"The clean {scope} folder is missing. pk3DS must unpack the clean GARC before the patch manifest is generated.");

            AddDirectoryDiff(manifest, scope, sourceRoot, targetRoot, fullReplacement: true);
        }

        string rawTargetRoot = GetLegacyRawTemplateSourceFolder();
        if (rawTargetRoot.Length != 0)
            AddDirectoryDiff(manifest, "raw", romfsPath, rawTargetRoot, fullReplacement: false);

        if (manifest.Files.Count == 0)
            throw new InvalidDataException("The legacy catch-zone templates do not differ from the currently loaded clean files.");

        string outputPath = GetPatchManifestPath();
        Directory.CreateDirectory(Path.GetDirectoryName(outputPath)!);
        File.WriteAllText(outputPath, JsonSerializer.Serialize(manifest, JsonOptions));

        long changedBytes = manifest.Files.Sum(z => z.Hunks.Sum(h => (long)Convert.FromBase64String(h.Data).Length));
        int deletedFiles = manifest.Files.Count(z => z.Operation.Equals("delete", StringComparison.OrdinalIgnoreCase));
        int patchedFiles = manifest.Files.Count - deletedFiles;

        return $"Generated catch-zone patch manifest: {game} ({patchedFiles.ToString(CultureInfo.InvariantCulture)} patched files, " +
               $"{deletedFiles.ToString(CultureInfo.InvariantCulture)} deleted files, {changedBytes.ToString(CultureInfo.InvariantCulture)} changed bytes). " +
               $"Saved to {outputPath}";
    }

    internal static string ApplyCurrentGameWorkingDirectoryPatches()
    {
        return ApplyCurrentGamePatches(scope => scope.Equals("encdata", StringComparison.OrdinalIgnoreCase)
                                             || scope.Equals("mapGR", StringComparison.OrdinalIgnoreCase),
            scope => Path.GetFullPath(scope));
    }

    internal static string ApplyCurrentGameRawPatches(string romfsPath)
    {
        if (string.IsNullOrWhiteSpace(romfsPath) || !Directory.Exists(romfsPath))
            throw new DirectoryNotFoundException("The loaded RomFS folder could not be found.");

        return ApplyCurrentGamePatches(
            scope => scope.Equals("raw", StringComparison.OrdinalIgnoreCase),
            _ => Path.GetFullPath(romfsPath));
    }

    private static string ApplyCurrentGamePatches(Func<string, bool> scopeFilter, Func<string, string> rootResolver)
    {
        CatchZonePatchManifest manifest = LoadCurrentGameManifest();

        int patched = 0;
        int alreadyPatched = 0;
        int deleted = 0;

        foreach (CatchZonePatchFile file in manifest.Files.Where(z => scopeFilter(z.Scope)))
        {
            string root = rootResolver(file.Scope);
            string path = ResolveSafePath(root, file.Path);

            if (file.Operation.Equals("delete", StringComparison.OrdinalIgnoreCase))
            {
                if (!File.Exists(path))
                {
                    alreadyPatched++;
                    continue;
                }

                byte[] existing = File.ReadAllBytes(path);
                VerifyExpectedSource(file, existing, path);
                File.Delete(path);
                deleted++;
                continue;
            }

            if (!file.Operation.Equals("patch", StringComparison.OrdinalIgnoreCase))
                throw new InvalidDataException($"Unknown catch-zone patch operation '{file.Operation}' for {file.Scope}/{file.Path}.");

            if (!File.Exists(path))
                throw new FileNotFoundException($"Required clean file was not found: {file.Scope}/{file.Path}", path);

            byte[] data = File.ReadAllBytes(path);
            string currentHash = ComputeSha256(data);

            if (currentHash.Equals(file.TargetSha256, StringComparison.OrdinalIgnoreCase))
            {
                alreadyPatched++;
                continue;
            }

            VerifyExpectedSource(file, data, path);

            foreach (CatchZonePatchHunk hunk in file.Hunks.OrderBy(z => z.Offset))
            {
                byte[] replacement = Convert.FromBase64String(hunk.Data);
                if (hunk.Offset < 0 || hunk.Offset > data.Length - replacement.Length)
                    throw new InvalidDataException(
                        $"Patch hunk is outside the file bounds: {file.Scope}/{file.Path} @ 0x{hunk.Offset:X}.");

                Buffer.BlockCopy(replacement, 0, data, hunk.Offset, replacement.Length);
            }

            string resultHash = ComputeSha256(data);
            if (!resultHash.Equals(file.TargetSha256, StringComparison.OrdinalIgnoreCase))
                throw new InvalidDataException(
                    $"Catch-zone patch verification failed for {file.Scope}/{file.Path}. Expected {file.TargetSha256}, got {resultHash}.");

            File.WriteAllBytes(path, data);
            patched++;
        }

        if (patched == 0 && deleted == 0 && alreadyPatched == 0)
            return string.Empty;

        return $"Catch-zone patch: {patched.ToString(CultureInfo.InvariantCulture)} files patched, " +
               $"{deleted.ToString(CultureInfo.InvariantCulture)} files deleted, " +
               $"{alreadyPatched.ToString(CultureInfo.InvariantCulture)} already patched.";
    }

    private static void VerifyExpectedSource(CatchZonePatchFile file, byte[] data, string path)
    {
        if (file.Length >= 0 && data.LongLength != file.Length)
            throw new InvalidDataException(
                $"Unexpected file length for {file.Scope}/{file.Path}. Expected {file.Length.ToString(CultureInfo.InvariantCulture)}, got {data.LongLength.ToString(CultureInfo.InvariantCulture)}.");

        string currentHash = ComputeSha256(data);
        if (!currentHash.Equals(file.SourceSha256, StringComparison.OrdinalIgnoreCase))
            throw new InvalidDataException(
                $"The file does not match the clean source used to build this patch: {file.Scope}/{file.Path}. " +
                $"Expected SHA-256 {file.SourceSha256}, got {currentHash}. Use a clean compatible dump.");
    }

    private static CatchZonePatchManifest LoadCurrentGameManifest()
    {
        string path = GetPatchManifestPath();
        if (path.Length == 0 || !File.Exists(path))
            throw new FileNotFoundException("No catch-zone patch manifest exists for the currently loaded game.", path);

        CatchZonePatchManifest manifest = JsonSerializer.Deserialize<CatchZonePatchManifest>(File.ReadAllText(path), JsonOptions)
            ?? throw new InvalidDataException("The catch-zone patch manifest is empty or invalid.");

        if (manifest.Format != CurrentFormat)
            throw new InvalidDataException($"Unsupported catch-zone patch format {manifest.Format}. Expected {CurrentFormat}.");

        string game = GetGameFolderName();
        if (!manifest.Game.Equals(game, StringComparison.OrdinalIgnoreCase))
            throw new InvalidDataException($"Catch-zone patch manifest is for {manifest.Game}, but the loaded game family is {game}.");

        return manifest;
    }

    private static void AddDirectoryDiff(
        CatchZonePatchManifest manifest,
        string scope,
        string sourceRoot,
        string targetRoot,
        bool fullReplacement)
    {
        sourceRoot = Path.GetFullPath(sourceRoot);
        targetRoot = Path.GetFullPath(targetRoot);

        if (!Directory.Exists(targetRoot))
            return;

        var sourceFiles = Directory.Exists(sourceRoot)
            ? Directory.GetFiles(sourceRoot, "*", SearchOption.AllDirectories)
                .ToDictionary(z => NormalizeRelativePath(Path.GetRelativePath(sourceRoot, z)), z => z, StringComparer.OrdinalIgnoreCase)
            : new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);

        var targetFiles = Directory.GetFiles(targetRoot, "*", SearchOption.AllDirectories)
            .ToDictionary(z => NormalizeRelativePath(Path.GetRelativePath(targetRoot, z)), z => z, StringComparer.OrdinalIgnoreCase);

        foreach ((string relative, string targetPath) in targetFiles.OrderBy(z => z.Key, StringComparer.OrdinalIgnoreCase))
        {
            if (!sourceFiles.TryGetValue(relative, out string sourcePath))
            {
                throw new NotSupportedException(
                    $"The legacy template adds a new file ({scope}/{relative}). " +
                    "The first patch format intentionally does not embed complete added game files. This file needs a semantic generator or a later delta format.");
            }

            byte[] source = File.ReadAllBytes(sourcePath);
            byte[] target = File.ReadAllBytes(targetPath);

            if (source.AsSpan().SequenceEqual(target))
                continue;

            if (source.Length != target.Length)
            {
                throw new NotSupportedException(
                    $"The legacy template changes the length of {scope}/{relative} ({source.Length} -> {target.Length}). " +
                    "The first patch format supports same-length byte replacements only.");
            }

            var hunks = BuildHunks(source, target);
            manifest.Files.Add(new CatchZonePatchFile
            {
                Scope = scope,
                Path = relative,
                Operation = "patch",
                Length = source.LongLength,
                SourceSha256 = ComputeSha256(source),
                TargetSha256 = ComputeSha256(target),
                Hunks = hunks,
            });
        }

        if (!fullReplacement)
            return;

        foreach ((string relative, string sourcePath) in sourceFiles.OrderBy(z => z.Key, StringComparer.OrdinalIgnoreCase))
        {
            if (targetFiles.ContainsKey(relative))
                continue;

            byte[] source = File.ReadAllBytes(sourcePath);
            manifest.Files.Add(new CatchZonePatchFile
            {
                Scope = scope,
                Path = relative,
                Operation = "delete",
                Length = source.LongLength,
                SourceSha256 = ComputeSha256(source),
                TargetSha256 = string.Empty,
            });
        }
    }

    private static List<CatchZonePatchHunk> BuildHunks(byte[] source, byte[] target)
    {
        var hunks = new List<CatchZonePatchHunk>();
        int i = 0;

        while (i < source.Length)
        {
            if (source[i] == target[i])
            {
                i++;
                continue;
            }

            int start = i;
            while (i < source.Length && source[i] != target[i])
                i++;

            int length = i - start;
            byte[] replacement = new byte[length];
            Buffer.BlockCopy(target, start, replacement, 0, length);

            hunks.Add(new CatchZonePatchHunk
            {
                Offset = start,
                Data = Convert.ToBase64String(replacement),
            });
        }

        return hunks;
    }

    private static string ResolveSafePath(string root, string relative)
    {
        string fullRoot = Path.GetFullPath(root);
        string normalizedRelative = relative.Replace('/', Path.DirectorySeparatorChar);
        string fullPath = Path.GetFullPath(Path.Combine(fullRoot, normalizedRelative));

        string prefix = fullRoot.EndsWith(Path.DirectorySeparatorChar)
            ? fullRoot
            : fullRoot + Path.DirectorySeparatorChar;

        if (!fullPath.StartsWith(prefix, StringComparison.OrdinalIgnoreCase))
            throw new InvalidDataException($"Unsafe path in catch-zone patch manifest: {relative}");

        return fullPath;
    }

    private static string ComputeSha256(byte[] data) =>
        Convert.ToHexString(SHA256.HashData(data)).ToLowerInvariant();

    private static string NormalizeRelativePath(string path) =>
        path.Replace(Path.DirectorySeparatorChar, '/').Replace(Path.AltDirectorySeparatorChar, '/');

    private static string GetPatchManifestPath()
    {
        string game = GetGameFolderName();
        if (game.Length == 0)
            return string.Empty;

        return Path.Combine(AppContext.BaseDirectory, PatchRootName, game + ".json");
    }

    private static string GetLegacyRawTemplateSourceFolder()
    {
        string game = GetGameFolderName();
        if (game.Length == 0)
            return string.Empty;

        string root = Path.Combine(AppContext.BaseDirectory, LegacyTemplateRootName);
        string preferred = Path.Combine(root, game, "raw");
        if (Directory.Exists(preferred))
            return preferred;

        string flat = Path.Combine(root, game + "_raw");
        return Directory.Exists(flat) ? flat : string.Empty;
    }

    private static string GetLegacyTemplateSourceFolder(string logicalFolder)
    {
        string game = GetGameFolderName();
        if (game.Length == 0)
            return string.Empty;

        string root = Path.Combine(AppContext.BaseDirectory, LegacyTemplateRootName);
        if (!LegacyFolderNames.TryGetValue(logicalFolder, out string[] candidates))
            candidates = [logicalFolder];

        foreach (string candidate in candidates)
        {
            string path = Path.Combine(root, game, candidate);
            if (Directory.Exists(path))
                return path;
        }

        foreach (string candidate in candidates)
        {
            string path = Path.Combine(root, game + "_" + candidate);
            if (Directory.Exists(path))
                return path;
        }

        return string.Empty;
    }

    private static bool IsGen6XYOrORAS() => Main.Config?.XY == true || Main.Config?.ORAS == true;

    private static string GetGameFolderName()
    {
        if (Main.Config?.ORAS == true)
            return "ORAS";
        if (Main.Config?.XY == true)
            return "XY";
        return string.Empty;
    }
}

internal sealed class CatchZonePatchManifest
{
    public int Format { get; set; }
    public string Game { get; set; } = string.Empty;
    public List<CatchZonePatchFile> Files { get; set; } = [];
}

internal sealed class CatchZonePatchFile
{
    public string Scope { get; set; } = string.Empty;
    public string Path { get; set; } = string.Empty;
    public string Operation { get; set; } = "patch";
    public long Length { get; set; } = -1;
    public string SourceSha256 { get; set; } = string.Empty;
    public string TargetSha256 { get; set; } = string.Empty;
    public List<CatchZonePatchHunk> Hunks { get; set; } = [];
}

internal sealed class CatchZonePatchHunk
{
    public int Offset { get; set; }
    public string Data { get; set; } = string.Empty;
}
